site_name: Object Squad Handbook
site_url: https://scality.github.io/citadel
repo_url: https://github.com/scality/citadel
edit_uri: 'edit/development/1.0/docs/'
theme:
  name: material
  palette:
    scheme: black
    primary: deep orange
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js
nav:
  - Requirements:
    - 'S3 Replication Monitoring': 'requirements/s3-replication-monitoring.md'
  - Design:
    - 'General': 'design/index.md'
    - 'Bucket Notifications': 'design/bucket-notification.md'
    - 'Object Lock': 'design/object-lock.md'
    - 'UTAPI': 'design/utapi.md'
    - 'Ballot Launcher': 'design/ballot-launcher.md'
    - 'Monitoring': 'design/monitoring.md'
  - Release:
    - 'General': 'release/index.md'
    - 'Disconnecting': 'release/disconnecting.md'
