site_name: Zenko Specifications
docs_dir: specs
theme:
    name: readthedocs
    custom_dir: template/
    extra_css:
        - template/classic.css
        - template/custom.css
    include_sidebar: false
